GET http://localhost:5000/meineprodukte/produktanlegen

###


POST http://localhost:5000/api/users/login
Content-Type: application/json

{"email": "hajih.wwi20@student.dhbw-heidenheim.de",
"password": "1234"}