GET http://localhost:5000/meineprodukte/produktanlegen

###

POST http://localhost:5000/meineprodukte/produktanlegen
Content-Type: application/json

{
    "produkt_ersteller" : "David",
    "produkt_bezeichnung": "Dildo",
    "produkt_mindestwert": "20€", 
    "produkt_beschreibung": "Angaben ohne Gewähr.",
    "produkt_bild" : "dick.png"
}